// The bundled map collection: web-optimized copies of the DM's default
// maps, generated by scripts/build-collection.mjs into public/collection/.
// Served as static files, so the app stays fully offline-capable once
// loaded; adding a map copies it into the local IndexedDB library.

export interface CollectionMap {
  id: string;
  name: string;
  /** Series / campaign folder the map belongs to. */
  folder: string;
  /** Path of the full map image, relative to public/collection/. */
  file: string;
  /** Path of the browsing thumbnail, relative to public/collection/. */
  thumb: string;
  width: number;
  height: number;
  /** Pixels per grid square in the optimized image, when known from the filename. */
  pps: number | null;
  gridW: number | null;
  gridH: number | null;
}

const BASE = `${import.meta.env.BASE_URL}collection/`;

export function collectionUrl(relativePath: string): string {
  return `${BASE}${relativePath}`;
}

let manifestPromise: Promise<CollectionMap[]> | null = null;

export function loadCollection(): Promise<CollectionMap[]> {
  if (!manifestPromise) {
    manifestPromise = fetch(`${BASE}manifest.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`manifest fetch failed: ${res.status}`);
        return res.json() as Promise<CollectionMap[]>;
      })
      .catch((err) => {
        manifestPromise = null;
        throw err;
      });
  }
  return manifestPromise;
}
