// The bundled SRD 5.1 monster stat blocks: public/srd-monsters.json,
// generated by scripts/fetch-srd-monsters.mjs and tracked in the repo (it's
// small text, unlike the map collection). Loaded lazily when the SRD browser
// opens; adding a monster copies it into the roster as a normal, fully
// editable enemy character — the JSON itself is never modified.
//
// SRD 5.1 content is CC-BY-4.0; the required Wizards of the Coast
// attribution is shown in the browser footer and in the README.

export interface SrdMonster {
  name: string;
  /** Size + creature type, e.g. "Small humanoid (goblinoid)". */
  type: string;
  /** Display challenge rating ("1/4", "5", …). */
  cr: string;
  /** Numeric CR for sorting/filtering. */
  crValue: number;
  ac?: number;
  hp?: number;
  speed?: string;
  str?: number;
  dex?: number;
  con?: number;
  int?: number;
  wis?: number;
  cha?: number;
  /** Full readable stat text: header line, senses/skills, traits, actions. */
  notes: string;
}

let monstersPromise: Promise<SrdMonster[]> | null = null;

export function loadSrdMonsters(): Promise<SrdMonster[]> {
  if (!monstersPromise) {
    monstersPromise = fetch(`${import.meta.env.BASE_URL}srd-monsters.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`SRD monsters fetch failed: ${res.status}`);
        return res.json() as Promise<SrdMonster[]>;
      })
      .catch((err) => {
        monstersPromise = null;
        throw err;
      });
  }
  return monstersPromise;
}

/** Required CC-BY-4.0 attribution for the SRD 5.1 content. */
export const SRD_ATTRIBUTION =
  'Monster stat blocks from the System Reference Document 5.1 by Wizards of the Coast LLC, ' +
  'licensed under the Creative Commons Attribution 4.0 International License.';
